### ISSUE TITLE
Word vectors instead of sentence vectors

### ISSUE THREAD

**Issue by iarroyof** [facebookresearch/fastText#101]
Hi all,

Someone can help me please? I'd like to infer sentence vectors by using fastText. I trained the model and I used the given example in the Github page:

> If you want to compute vector representations of sentences or paragraphs, please use:
> `$ ./fasttext print-vectors model.bin < text.txt`

In my case the file `text.txt` contains a sentence by line. However, what I get as result is a file with a word representation by line, instead of a sentence representation by line. It is really possible to infer sentence representations?

Thank you.

**Comment by spate141** [comment]
how are you creating model.bin? skipgram, cbow, or supervised ?

I guess, supervised one can give you vector of entire sentence.

**Comment by iarroyof** [comment]
Hi @spate141, thank you for replying.

I'm using the `skipgram` option, i.e.

```$ ./fasttext skipgram -input data.txt -output model```

My `data.txt` is the Spanish Wikipedia. Some moments ago I was thinking to generate sentence strings separated by '_' instead of ' '. Do you think it would work?

**Comment by EdouardGrave** [comment]
Hi @iarroyof,
as @spate141 has noted, fastText outputs sentence representations only for supervised models (trained using `./fasttext supervised`).

A solution to obtain a representation of a sentence from an unsupervised model is to take the average of the vectors of words from the sentence (bag-of-words representation). If doing so, you should normalized the word vectors first (so that they have a norm equal to one).

We are working on developing better sentence representations from unsupervised models. May I ask what is your application of sentence representations?

Thanks!

**Comment by iarroyof** [comment]
Hi @EdouardGrave , Thank you.

I'm now exploring the code for taking into account suggestions from you and @spate141 .

Actually there are some related applications I'm working on and they require different levels of phrase length analysis (words, multi-word phrases, sentences and snippets). These different phrase lengths are thought as result from corresponding different filtering levels (in the sense of signal processing), where these levels are suitable to NLP tasks such as entity relationship extraction, word/phrase/sentence semantic similarity and text summarization. For the sake of curiosity, I just used the '_' approach for clustering verbal periphrases and it worked very well. Probably for more complex phrases the thing will change.
