### ISSUE TITLE
Deterministic output from vector training

### ISSUE THREAD

**Issue by ZexCeedd** [facebookresearch/fastText#116]
I get different vector outputs from each run.
How do I set a seed to ensure determinism?

I'm referring to training word vectors and not the predictive tasks.

Thanks

**Comment by EdouardGrave** [comment]
Hi @ZexCeedd,

If you want to get the same vectors from two runs, you have to use only one thread for training (using the command line option `-thread 1`). Otherwise, because of the optimization algorithm used by fastText (asynchronous stochastic gradient descent, or Hogwild), the obtained vectors will be different, even if initialized identically.
