### ISSUE TITLE
Representing P most frequent words without n-grams

### ISSUE THREAD

**Issue by jayantj** [facebookresearch/fastText#16]
Quoting from the last paragraph of section 3 in the [word representation paper](https://arxiv.org/pdf/1607.04606v1.pdf) - 

`To improve the efficiency of our model, we do not use n-grams to represent the P most frequent words in the vocabulary. There is a trade-off in the choice of P, as smaller values imply higher computational cost but better performance.`

I couldn't find any further references to it in the implementation details or the released code. I was looking to use this to directly imitate the original skipgram model. Was this dropped from the final implementation? 

The best alternate (hack-y) way to do this seems to modify the computeNgrams method in Dictionary. Would simply making it do nothing be a correct approach?

Sorry for raising this as an issue, wasn't sure where else to ask this.

**Comment by gojomo** [comment]
I also couldn't find any equivalent to the 'Subword Information' paper's `P` in fastText. 

But rather than modifying `computeNgrams` source, it should be enough to just provide an extreme `-minn` or `-maxn` parameter. 

A `minn` larger than 'maxn' should mean line https://github.com/facebookresearch/fastText/blob/55ba6b505004539d3621d8eb5a10d5259faa4bb2/src/dictionary.cc#L128 is never reached, so no word ever decomposed into char n-grams, so the fastText code equivalent to classic word-only word2vec. So running fastText with `-maxn 0` seems sufficient to disable char n-grams.

**Comment by Shodipo-Ayomide00** [comment]
Am I allowed to give a comment

**Comment by piotr-bojanowski** [comment]
Hi,

You are right, the parameter was removed from the final implementation. Given that the code is much more efficient not than then, this parameter was not critical. We may consider re-implementing it later if useful applications are found.

Best,

Piotr

**Comment by Shodipo-Ayomide00** [comment]
I think it should be done now it's not about how many codes are there it is
ABOUT the site security because if anyone else finds out you have a hole in
your site it will bring hackers to test their skills and that is nither
good for the server on the site  so I suggest it should be fixed latest
this week

**Comment by jayantj** [comment]
Thanks a lot for the helpful responses, @gojomo and @piotr-bojanowski
