### ISSUE TITLE
Pre-trained Polish word vectors based on mistokenized words

### ISSUE THREAD

**Issue by mciura** [facebookresearch/fastText#180]
Many words in the pre-trained Polish model start with DOUBLE LOW-9 QUOTATION MARK (U+201E), which is used in Polish spelling to open quotations. Here is just the very beginning of the list (as Python strings):

u'\u201eradio', u'\u201eczarne', u'\u201emewa', u'\u201ekampinos', u'\u201egra', u'\u201egryf', u'\u201eksi\u0119ga', u'\u201eksi\u0119gi', u'\u201eall', u'\u201ejeden', u'\u201et\u0119cza', u'\u201eanother', u'\u201etaniec', u'\u201eover', u'\u201efilm'

**Comment by piotr-bojanowski** [comment]
Hi,

We recently pushed the script that we used to download and pre-process the wikipedia data:
https://github.com/facebookresearch/fastText/blob/master/get-wikimedia.sh

In the normalization step, some of the unicode characters for double quotes (U+201C for instance) are replaces by the standard quotes. If you want to obtain a better model for Polish you can add some normalization steps in that script, and re-train the model.

On the other hand, better (more rigorous) normalization is on our list of tasks. In the meantime, because of the frequency of such punctuation, I believe that this should not be to much of an issue (provided that the same string, without the U+201E exists in the dictionary).

Thanks for your feedback!
