### ISSUE TITLE
Word vectors obtained for non-existing words

### ISSUE THREAD

**Issue by jkleiser** [facebookresearch/fastText#181]
I have produced a model.bin from a small file containing Norwegian tokenized text (just 211 chars) by doing this:
```
./fasttext skipgram -input data.txt -output model
```
What surprises me, is that if I try to obtain the word vector for a non-existing word like "fooXYZ" by doing this:
```
echo "fooXYZ" | ./fasttext print-vectors model.bin
```
then I get a real-looking vector, and I am not able to tell this vector from the ones I get when the input is a real word from my data.txt. I have tried a few non-existing words, and the vectors I get don't even seem to be close (by Cosine similarity).

I also have problems understanding what determines which (very few, very short) words that find their way into the model.vec file when I do the `./fasttext skipgram`.

I suspect my lacking knowledge about the proper use of fasttext may be the reason for my questions here. ;-)

**Comment by jkleiser** [comment]
I think I have just misunderstood the purpose and contents of the .bin and .vec files produced by the `./fasttext skipgram`. As it appears to me now, the .bin file is not a model containing word vectors; its content is about how sequences of characters may form words in a way that reflects the patterns in the input text. Therefore, by using `./fasttext print-vectors`, one may ask for the vector of any word, real or made-up.
Exactly what determines which words that find their way into the model.vec file, and for what purpose these (few) words can be used later, that is still not clear to me.

**Comment by ardeego** [comment]
@jkleiser To get any useful model out of fastText (and other word vector implementation) you have to use **much** more data. The more, the better. Gigabytes of it ideally. When you train the model you set quite a few parameters (even though you might not be aware of it when you use the example scripts). For example ``-minCount`` (which is set to 5 by default) says: include only words in the model that occur at least 5 times in the training corpus, otherwise we just drop them. So anything that has an occurrence less than 5 will not show up in the ``.vec`` file.

``-minn`` and ``-maxn`` determine the minimum and maximum length of char n-grams in which your input data is chopped up. The vectors for the chopped up words (think of them as fixed size "syllables") is what goes into the ``.bin`` file. Finally, when you look up a word that is *outside* the vocabulary you have trained on, a vector is generated on the fly by *simply computing the average* of the word vectors corresponding to the n-grams it is made up from (see [fasttext.cc, line 28-37](https://github.com/facebookresearch/fastText/blob/master/src/fasttext.cc#L28-L37)).

**Comment by jkleiser** [comment]
@ardeego Thanks! I'm a little bit wiser now. ;-)
