### ISSUE TITLE
Question about the "Advanced readers: skipgram versus cbow" part of the tutorial.

### ISSUE THREAD

**Issue by arnor-sigurdsson** [facebookresearch/fastText#194]
Hello and thank you for this awesome library!

Looking over the cool new tutorial and noticed something that made me pause for a bit. When discussing the difference between CBOW and skipgram, the tutorial states:

> The skipgram model learns to predict a target word thanks to a nearby word. On the other hand, the cbow model predicts the target word according to its context. The context is represented as a bag of the words contained in a fixed size window around the target word.

![cbo_vs_skipgram](https://cloud.githubusercontent.com/assets/13853804/25653118/cb7aa9d4-2feb-11e7-8924-e5e03437bf42.png)

Maybe I am misunderstanding, but to me this seems a little bit misleading. I totally agree with the description of CBOW, but my understanding of skipgram was that it tries to predict the context words around the same input word, as illustrated in the paper by Mikolov et al. (Efficient Estimation of Word Representations in Vector Space):

<img width="642" alt="screen shot 2017-05-03 at 10 35 41" src="https://cloud.githubusercontent.com/assets/13853804/25653240/53673ace-2fec-11e7-87d7-108977950348.png">

Therefore, in the case of the leather jacket the input would always be "fine", but we are trying to predict "selling", "these", etc.

All the best,
Arnor

**Comment by EdouardGrave** [comment]
Hi @arnor-sigurdsson,

The figure is correct, since there is no real distinction between "context" and "input" words for the skipgram algorithm. Indeed, all words of the sentence will be considered as "input" word. Thus, all pairs of words `(w_i, w_j)` such that `|i - j| < ws` will be used as training example, where `w_i` is the "input" word and the goal is to predict the "context" word `w_j`.

Best,
Edouard
