### ISSUE TITLE
Cannot load wiki.de.bin due to C++ extension failed to allocate the memory

### ISSUE THREAD

**Issue by amitmac** [facebookresearch/fastText#197]
I am trying to import fasttext pre-trained model for english and german language but getting this exception. System RAM is 120GB. Here is the code.

```
import fasttext
fasttext.load_model('wiki.de.bin')
```

**Comment by cpuhrsch** [comment]
Hello @amitmac,

This looks like you're using some Python bindings. Our recent changes aren't backwards compatible, so these bindings might need to be updated, or the underlying fasttext distribution needs to be rebuild. I'm not sure if I can be of help for that, since these bindings are outside of this repository as far as I can tell.

Thank you
Christian

**Comment by lxw0109** [comment]
Hello @amitmac , did you get rid of the problem? I came across the same situation(`Exception: fastText: Cannot load foo_bar.bin due to C++ extension failed to allocate the memory`). Thank you ~

**Comment by amitmac** [comment]
Hi @Ixw0109, I ended up using their command through terminal for this. 
./fasttext print-word-vectors
You can see documentation.
If you want to use it using python may be you can go with subprocess module.
