### ISSUE TITLE
Wrong format in pretrained french vectors  (wiki.fr.vec)?

### ISSUE THREAD

**Issue by aurlien** [facebookresearch/fastText#204]
When parsing the wiki.fr.vec file, I observe some anomalies in the file. 

I use the following python code, where 'filename' is the name of wiki.fr.vec:

```Python
with open(filename) as f:
            i = 2
            
            # The first line only contains information about the file itself
            f.readline()

            for line in f:
                values = line.split()

                word = values[0]
                coefs = np.asarray(values[1:], dtype='float32')
   
                index_to_word[i] = word
                embedding_matrix.append(coefs)
                i += 1
```

Most lines look like expected:
(line 21):
`un -0.19326 -0.023721 0.0096097 0.24218 0.37374 -0.087953 0.061238 0.16691 ...`

However, not all lines follow this format. For instance (notice the extra »):
(line 1152424):
`hussarde » -0.19917 0.046022 0.013674 -0.18072 -0.0029925 -0.27038 0.23088 ...`

Is there some meaning in these »'s, or is the format wrong?

**Comment by cpuhrsch** [comment]
Hello @aurlien,

It is often difficult to remove all esoteric characters from large text corpora. It is often also not important to do this very, very well, since such words tend to be infrequent and the data is large enough. For example, the word you're mentioning is on line 1152424, which means it not even in the top 1 million most frequent words. If you were to find these artifacts in more common words (e.g. top 100k or so), it'd be more worrying.

I'm closing this issue for now, since it is also a bit older, but please feel free to reopen it at any time, if it's still current or not resolved.

Thanks,
Christian
