### ISSUE TITLE
Unsupervised Model Training takes too long?

### ISSUE THREAD

**Issue by Mustyy** [facebookresearch/fastText#210]
I started going through the tutorial and training the unsupervised model on wikidata about 12g of data
the model is taking 10 hours
is this normal?

**Comment by cpuhrsch** [comment]
Hey @Mustyy,

Could you provide the details of the steps you're taking to train so I can reproduce the behavior on my end? Make sure you're compiling the binaries in 'opt' mode by typing `make clean && make opt` on Linux.

Thank you,
Christian

**Comment by onurgu** [comment]
Hi @Mustyy,

It trains around 30000 words/sec with 10 cores in my experience. What is the value of this statistic for you?

**Comment by Mustyy** [comment]
Hey guys, 

I actually just followed the tutorial
My machine is 4 cores on an aws ubuntu instance.
I will double check make clean && make opt

last time I checked it was processing about 70K words/sec

**Comment by Mustyy** [comment]
keep in mind that also my wiki file is about 12Gb rather than the 1 billion bytes given in the tutorial

**Comment by cpuhrsch** [comment]
Hello @Mustyy, it appears that your performance is within range for your usecase. In fact 70K words/sec/thread is quite good in my experience. We've also not noticed any perf regressions on our end. Since you're using a lot more data you can also try reducing the number of epochs. You might not need as many passes as for the 1Gb case. I'll close the task for now, but please feel free to reopen, if you think it's not resolved. Keep in mind however, that it is difficult to resolve performance problems from afar as it greatly depends on the environment.
