### ISSUE TITLE
Question for test model

### ISSUE THREAD

**Issue by zhongboyin** [facebookresearch/fastText#228]
How to watching the specific precision and recall of every label?

**Comment by cpuhrsch** [comment]
Hello @zhongboyin,

You can print the probability of each label using predict-proba. You can then write a small preprocessing script (for example python) to calculate precision and recall. Consider [this example](http://scikit-learn.org/stable/auto_examples/model_selection/plot_precision_recall.html). We don't plan to support much more functionality than this, since it's easy to calculate these statistics with other, orthogonal tools and we aim to make sure our codebase stays minimal and efficient. Also see #261 for a similar issue. I'm going to close the issue, but feel free to reopen at any time if it's still current / hasn't been resolved.

Thanks,
Christian
