### ISSUE TITLE
do we support utf-8?

### ISSUE THREAD

**Issue by yudong27** [facebookresearch/fastText#23]
Hello, thank you for your contribution.

I performed some tests with classification on the Chinese text, while an error occurred as follow:
- terminate called after throwing an instance of 'std::bad_array_new_length'
-  what():  std::bad_array_new_length
- Aborted (core dumped)

Through many debugging， the error is located in the code of function of save and load in dictionary.cc.
In function Dictionary::save, 0 is saved as the end of word.data, as following code.
- ofs.write(e.word.data(), e.word.size() \* sizeof(char));
- ofs.put(0);

It's ok when the text is written in English, while it maybe incompatible with other languages.
Will the software support utf-8 in future versions?

**Comment by piotr-bojanowski** [comment]
Hi, 

Is the dataset you are using public? It would be nice if you could provide more details on the run that generated this bug so that we can reproduce it. 
As for now, our code is fully utf-8 compatible and we have successfully trained models on Japanese, Arabic and European languages with utf8 characters.

Best regards

**Comment by StevenLOL** [comment]
Fasttext do support utf-8,  I had run my experiments on Chinese text too, no problem encountered.  Show us your arguments / dataset used  if you need any further assistance.

**Comment by hodzanassredin** [comment]
I tested fast text with russian corpora and P and R are very low. 

> P@1: 0.06
> R@1: 0.06

Corpora has about 1.5 k labels and about several thousands docs. Our standard classifier shows fscore about 0.5 on the same corpora.  
I could not send you whole corpora but only limited for only 20 docs per label.
Output of raw text corpora limited to 20 docs per lable:
```
$ fastText/fasttext supervised -input fast_text.txt -output context.model
Read 1M words
Progress: 100.0%  words/sec/thread: 291778  lr: 0.000001  loss: 17.748674  eta: 0h0m
Train time: 2.000000 sec
$ ./fastText/fasttext test context.model.bin fast_text.txt 1
P@1: 0.0513
R@1: 0.0513
Number of examples: 13638
```
Another attempt was to classify the same corpora, but with removed punctuation and oher stuff . 
Result:

> P@1: 0.134
> R@1: 0.134

And for full cleaned corpora:
```
$ fastText/fasttext supervised -input fast_text.txt -output context.model
Read 112M words
Progress: 100.0%  words/sec/thread: 726253  lr: 0.000001  loss: 5.564087  eta: 0h0m
Train time: 100.000000 sec
$ ./fastText/fasttext test context.model.bin fast_text.txt 1
P@1: 0.167
R@1: 0.167
Number of examples: 295968
```
Also i tested transliterated unclean corpora and result was:

> P@1: 0.0791
> R@1: 0.0791

So in my case problem is not in encodings at all but in something other.
Docs are texts crawled from html pages.
So why results are so bad? 
I suppose that this is because of really bad corpora. And it is not clear from docs, do you expect some cleaned docs or raw texts? Seems that texts after tokenization and cleaning show better results. I tested everything with default params.
[fast_text_ru_limited_clean.zip](https://github.com/facebookresearch/fastText/files/459705/fast_text_ru_limited_clean.zip)
[fast_text_ru_limited_raw.zip](https://github.com/facebookresearch/fastText/files/459706/fast_text_ru_limited_raw.zip)

**Comment by piotr-bojanowski** [comment]
Hi,

thanks for your insightful comment. Indeed, for good performance, removing non discriminative features such as html tags is recommended. For the word-vector training using sub-word information we pre-processed wikipedia dumps using Matt Mahoney's perl scripts found here: http://www.mattmahoney.net/dc/textdata.

**Comment by hodzanassredin** [comment]
Seems that nobody is going to answer?

**Comment by hodzanassredin** [comment]
Was not able to solve that issue. But It is hard to me to undestand c++. Decided to rewrite it in [Dot net](https://github.com/hodzanassredin/fastText). 
Hope now I'll be able to find a reason for that problem with russian texts .
