### ISSUE TITLE
What does the bucket option do?

### ISSUE THREAD

**Issue by nrasiwas** [facebookresearch/fastText#24]
I see it in both word vector learning and supervised classification. 

-bucket       number of buckets [2000000]

**Comment by EdouardGrave** [comment]
Word and character ngrams features are hashed into a fixed number of buckets, in order to limit the memory usage of the model. The option -bucket is used to fix the number of buckets used by the model.

For questions about the functionalities, please use the Facebook page (https://www.facebook.com/groups/1174547215919768) or the Google group (https://groups.google.com/forum/#!forum/fasttext-library) instead of Github issue. Thanks!

**Comment by dcsan** [comment]
btw facebook and google groups are blocked in china, so some other forum (Discourse forum) that isnt blocked would be very helpful 👯‍♂️

**Comment by HQuality** [comment]
> btw facebook and google groups are blocked in china, so some other forum (Discourse forum) that isnt blocked would be very helpful
or, well, move to other country that isn't blockING would be very helpful also
