### ISSUE TITLE
why was printSentence delimiter changed to space ?

### ISSUE THREAD

**Issue by ajkl** [facebookresearch/fastText#246]
With the delimiter being space now (insted of tab) with this change -
 https://github.com/facebookresearch/fastText/commit/a9d7c2c6393ccca7276df0699441509fe95367e5 how would you seperate the vector from the sentences if you dump the vectors to a file ?
Only way i can think of is to get last n space separated values from each line where n is dimension of the embeddings

**Comment by cpuhrsch** [comment]
Hello @ajkl,

One possible option here might be to use the linux program `cut` (if this is the platform you're using). `cut` allows you to specify a range of fields and you can set the delimiter to be a space. You could specify to print all but the first column per line. Since this a general problem (extracting columns from text) and not specific to fastText, you'll probably find the best help over at [Stackoverflow](https://stackoverflow.com/) or other related online forums.

Thanks,
Christian

**Comment by ajkl** [comment]
Yes, I ended up using cut.
