### ISSUE TITLE
Memory usage of models

### ISSUE THREAD

**Issue by spate141** [facebookresearch/fastText#248]
I have a sample model trained with latest fasttext code, model.ftz is of size 388MB, when I load the model; memory usage is ~1.6GB. Any idea on this?

**Comment by cpuhrsch** [comment]
Hello @spate141,

This extra memory is likely to come from additional memory that is allocated on the fly to improve performance. Do you have a particular application in mind that will require you to use as little RAM as possible?

Thanks,
Christian

**Comment by spate141** [comment]
@cpuhrsch Yes, I was wondering to setup a tree structure of models in hierarchy, and for this if I can load multiple (ex.: 10-15 ?) models which can fits into memory by using as little RAM as possible.

**Comment by cpuhrsch** [comment]
Hello @spate141,

I see. So far we haven't spend a lot of time optimizing the actual RAM usage. As in common you can often tradeoff RAM for compute. Since we try to optimize for wall clock runtime, we're willing to trade in some RAM. Ideally this would be something that one can parameterize. This is a legitimate usecase, but I can't guarantee and timeline for it's development. I'll add it to the list of things to do.

Thanks,
Christian
