### ISSUE TITLE
How is one line per document parsed for skipgram

### ISSUE THREAD

**Issue by nrasiwas** [facebookresearch/fastText#25]
I have a file with one sentence per line. There is no direct relation between two lines. 

e.g.

Sports line talks about sports and activities related to sports like stamina. 
Politics line talks about politics and related concepts like election.

So if the context is say 5 words, will it consider context across sentences? Will "Politics" be considered a context of "stamina"?

**Comment by EdouardGrave** [comment]
Each line is processed independently. In your example, "Politics" will not be considered as a context of "stamina".

For questions about the functionalities, please use the Facebook page (https://www.facebook.com/groups/1174547215919768) or the Google group (https://groups.google.com/forum/#!forum/fasttext-library) instead of Github issues. Thanks!
