### ISSUE TITLE
What is the source of char n-grams ?

### ISSUE THREAD

**Issue by sam-iitj** [facebookresearch/fastText#263]
Are character n-grams present in the pre trained word vectors ?. I tried running the pring-word-vectors function, which prints the word vectors for each of the word from a text file. Fasttext essentially was generating the char **_n-grams_** for each word and then hashing each of those character **_n-grams_** to a value which is greater than **_nwords_._** But I was not able to figure out, from where it was getting the vector representation for the char n-grams. If we look at the loadVectors function, the last loop in the function is only going till **_n_** not to _**n + number of buckets.**_.

**Comment by cpuhrsch** [comment]
Hello @sam-iitj,

The character ngrams are retrieved from the dictionary for each word. Look at the following excerpt.

```

void FastText::getVector(Vector& vec, const std::string& word) const {
  const std::vector<int32_t>& ngrams = dict_->getSubwords(word);
  vec.zero();
  for (auto it = ngrams.begin(); it != ngrams.end(); ++it) {
    vec.addRow(*input_, *it);
  }
  if (ngrams.size() > 0) {
    vec.mul(1.0 / ngrams.size());
  }
}
```

The function 'getSubwords' will retrieve all indicies within the range of nwords to nwords + bucket and look up the corresponding vector in the input matrix. It will then add these vectors to the word vector and print the overall result.

I'm closing the issue to indicate that the question was answered. Feel free to reopen if the explanation isn't clear.

Thanks,
Christian

**Comment by cryoff** [comment]
Hello! I have another question on the same issue (seemingly).
I have been trying to import embeddings into my java program. In order to do so, I first used a solution given in 
[#289](https://github.com/facebookresearch/fastText/pull/289)
However, when I import those ngram vectors, I can't get the embedding for weird OOV ngrams/words.
For example, I can't get the vector for 'a^3'. (using German model trained on Wikipedia)
However, when I use fasttext directly using the same model, I get the embedding vector.
So, is there something off with the ngram embedding extraction procedure?
