### ISSUE TITLE
Strange label prediction

### ISSUE THREAD

**Issue by adamkrajcs** [facebookresearch/fastText#379]
I've trained fasttext on 500000 job post text. After the training I tried to predict label for "backbone" word.
It gives back __label__119 with high probability
./fasttext predict-prob model_job__400_0.60_n_2.bin -
backbone
__label__119 0.994148

If I simply just grep on that word in the training data:
grep backbone jobs.preprocessed.txt | cut -d" " -f1 | sort | uniq -c
      3 __label__201
      7 __label__283
      2 __label__319
      1 __label__363
      2 __label__37
      1 __label__386
      2 __label__393
      1 __label__394
      6 __label__69
      7 __label__70
      8 __label__73
    140 __label__75
      2 __label__76
     10 __label__79

I got totally different labels and the __label__119 is in the training data at all.

**Comment by cpuhrsch** [comment]
Hello @adamkrajcs,

Thank you for your post. You might find more support for this kind of issue within one of our community boards. In particular, the Facebook group has many ML experts who are keen on discussing applications of this library.

Specifically, there is a

[Facebook group](https://www.facebook.com/groups/1174547215919768/)
[Stack Overflow tag](https://stackoverflow.com/questions/tagged/fasttext)
[Google group](https://groups.google.com/forum/#!forum/fasttext-library)

If you do decide to move this to one of our other community boards, please consider closing this issue.

Thanks,
Christian

**Comment by Celebio** [comment]
Hi @adamkrajcs ,
Indeed, it is strange the __label__119 doesn't appear once. fastText constructs the word vector from the subwords as well, and if the subwords are all very discriminant for __label__119 you may end up with what you observe. However, it is more likely you have an issue elsewhere. May be the `cut` command removes it (if you have multiple labels per line for example). You may want to try `grep backbone jobs.preprocessed.txt | sort | uniq -c`.

I am closing this issue now since it is quite old and you probably found the error in the meantime.
Please feel free to re-open it if you observe it again.
Best regards,
Onur
