### ISSUE TITLE
How to to see the parameters of trained models 

### ISSUE THREAD

**Issue by seemamishra33** [facebookresearch/fastText#418]
I am trying to classify (./fasttext supervised -input train.txt -output model)my data sets and I want to see what are the parameters of my trained model I have got. I tried using model.args but it says command not found.

**Comment by EdouardGrave** [comment]
Hi @seemamishra33,

Have you tried using the `dump` subcommand?

To get the hyper-parameters of a trained model, you can do:
```
./fasttext dump MODEL_FILENAME args
```
Instead of `args`, you can use `dict` to get the vocabulary corresponding to the model, `input` to get the input embeddings or `output` to get the classifier weights (in case of a supervised model) or the output embeddings (in case of an unsupervised model).

Best

**Comment by seemamishra33** [comment]
Thanks a lot for reply
Well I just started using fasttext so, I am still learning. But I think
your response really helps.

Thanks
