### ISSUE TITLE
file src／dictonary.cc，line 270   Abort trap: 6

### ISSUE THREAD

**Issue by aurora5161** [facebookresearch/fastText#42]
Dear author:
Thank you for your contribution. I download and test on ag_news data. my command are below:
1.  .／fasttext supervised -input .／data／ag_news.train -output model -dim 10 -lr 0.1 -wordNgrams 2 -minCount 1 -bucket 10000000 -epoch 5 -thread 4
2.  .／fasttext predict model.bin .／data／ag_news.test
However，I get a mistake:
Assertion failed:（lid < nlabels_），function getLabel，file src／dictionary.cc， line 270.
Abort trap: 6

Would you give me a help，Thank you very much!

**Comment by mcat-ee** [comment]
+1

**Comment by mcat-ee** [comment]
I realise from your code sample this isn't the case for you, but I was getting the following abort trap 6 because I was using the incorrect parameter combinations

**Commands I was using**
`./fasttext skipgram -input train.txt -output model`
`./fasttext test model.bin text.txt `
`Assertion failed: (counts.size() == osz_), function setTargetCounts, file src/model.cc, line 157.
`

**Commands I should have been using**
`./fasttext supervised -input train.txt -output model`
`./fasttext predict model.bin text.txt`

**Comment by aurora5161** [comment]
I found author update the source and readme file，After recompiling the source，the mistake disappear. However，the prediction output vector is null. I don't know why. can anybody help me ？Thank you very much!

**Comment by EdouardGrave** [comment]
The output `fasttext predict` is one label per line, not vectors.

**Comment by aurora5161** [comment]
Thank you very much ，my problem was solved，I should run the code according to file classification-results.sh
