### ISSUE TITLE
Prediction probability greater that at higher decimal points and how the features have been extracted?

### ISSUE THREAD

**Issue by tiru1930** [facebookresearch/fastText#455]
Hi 

I am new to this library use, sorry if this query make silly.

1. I have trained fasttext classifier on custom data, and when i see the prediction score on my testing it is greater than 1 , examples 

**1.0000100136**
--
**1.0000013113**
0.9999163151
**1.0000046492
1.0000041723
1.0000100136
1.0000084639**
0.999820292
0.5939040184

2.If test with some random label data which is not seen during the training , those random quires also having high score, if remove certain words from query then score is decreasing. what i have observed is if high frequency words in the corpus present in the random query , it is mapping one of the label with high score. So while considering the n-gram feature does fasttext  removes the high frequency words?
or how can we reduce score of random query which i had mentioned in above case.

**Comment by EdouardGrave** [comment]
Hi @tiru1930,

1. The fact that the probability is sometimes larger than 1.0 is due to numerical approximations.

2. The standard way to deal with "random queries" is to also add some of these random examples to the training data, with a dummy label. When doing this, the classifier will not have to assign all the probability (and thus, high scores) to the "true" classes when encountering a random query.

Best,
Edouard.
