### ISSUE TITLE
words hypersphere from a seed word

### ISSUE THREAD

**Issue by giodegas** [facebookresearch/fastText#48]
After training with a large corpus, given a word w, would it be possible with fasttext have a list L of all words contained in a hypersphere of radius R?

something like:

```
L = hypershere(w,R)
```

**Comment by EdouardGrave** [comment]
We will look at adding a feature to compute the k nearest neighbors of a query word. However, this is not on the priority list for the moment, since it could be done using third party libraries, by loading the `.vec` file.

**Comment by cpuhrsch** [comment]
Hey @giodegas, there is a new subcommand called "nn" that you can try. It can be used to enumerate the nearest neighbors around a given word. I'm taking note of this feature request for now and I'm closing the task since it's an old issue without much activity. Please feel free to reopen it at any point and thank you for your post.
