### ISSUE TITLE
Out of vocab word vectors predicted using CLI and python package are different.

### ISSUE THREAD

**Issue by icegeek22** [facebookresearch/fastText#490]
I train a cbow model using fasttext CLI and another using the fasttext python package on the same text corpus. Now when I predict out of vocab words using both the models, the 2 vectors are different.  Since both the models are trained on the same text corpus, why are the predicted word vectors not same?

**Comment by EdouardGrave** [comment]
Hi @icegeek22,

There is some randomness in the training process of fastText, due to the use of the [Hogwild algorithm](https://papers.nips.cc/paper/4390-hogwild-a-lock-free-approach-to-parallelizing-stochastic-gradient-descent). Hence, running fastText twice on the same dataset will give different word vectors. One way to remove the randomness is to use a single thread when training the model.

It is also possible to learn a linear transformation to "align" the word vectors corresponding to two different runs of fastText (e.g. using the method described in this [paper](https://arxiv.org/abs/1309.4168)).

Best,
Edouard.
