### ISSUE TITLE
Does FT learn embedding for n-grams as well? 

### ISSUE THREAD

**Issue by omerarshad** [facebookresearch/fastText#491]
1) In supervised Fasttext mode, does it learn embeddings for n-grams as well or does it add uni grams to make n-grams?
2) Does it take sub words into account in supervised learning?

**Comment by EdouardGrave** [comment]
Hi @omerarshad,

1. In supervised mode, fastText learns embeddings for word n-grams. In order to bound the memory used by the model, the word n-grams are hashed into a fixed number of buckets, and there is one embedding for each bucket. Thus, if there are collisions, multiple n-grams will share the same embedding. The number of bucket can be set with the command line option `-bucket`, and is equal to 2M by default. The maximum length of word n-grams can be set with the command line option `-wordNgrams` and is equal to 1 by default.
2. By default, the supervised mode does not use subwords. This can be changed by using the command line options `-minn` and `-maxn` (both are equal to 0 by default), which set the minimum and maximum length of the subwords that are taken into account. A good starting point is probably `-minn 4 -maxn 4`.

Best,
Edouard.

**Comment by sipan17** [comment]
Hi @EdouardGrave, how can I obtain the embeddings after the training is complete?
