### ISSUE TITLE
Can -input be /dev/stdin?

### ISSUE THREAD

**Issue by pengyu** [facebookresearch/fastText#522]
I tried `-input` with `/dev/stdin` (for skipgram). But it seems fastText hangs there forever. I also see the following code.

```
  if (args_->input == "-") {
    // manage expectations
    throw std::invalid_argument("Cannot use stdin for training!");
  }
```
I don't see an I/O function used in fastText that disallows stdin. It seems that this is a bug and can be fixed using something mentioned here.

https://groups.google.com/forum/#!topic/comp.lang.c++/ThzD5u22UyY

Can someone fix it? Thanks.

**Comment by danieldk** [comment]
`FastText::trainThread` divides data across threads. In order to do so, it has to determine the overall size of the data and then seek to the start of the chunk for that thread. You (generally) can't:

* Do seeks on stdin.
* Determine the size of stdin (except by reading the whole stream).

So, the only straightforward way to work with `stdin` would be reading all the data into memory.

**Comment by EdouardGrave** [comment]
Hi @pengyu,

As explained by @danieldk, fastText splits the data across threads by having each thread read a different part of the training file. FastText also needs to read the full file before training, to build the vocabulary. These reasons makes it impossible to use `stdin` for the moment.

Best,
Edouard.
