### ISSUE TITLE
fastText for NER

### ISSUE THREAD

**Issue by PrashantRanjan09** [facebookresearch/fastText#531]
I read that using fastText embeddings can improve the NER. 
Can you please tell me how can we use fastText embeddings to get the NERs?

**Comment by loretoparisi** [comment]
@PrashantRanjan09 can you point us to the referred paper?

**Comment by sughodke** [comment]
It must be this one. 
https://arxiv.org/abs/1709.04820

**Comment by EdouardGrave** [comment]
Hi @PrashantRanjan09,

A standard approach to improve named entity recognition with continuous word representations is to use word embeddings, trained on large amount of unlabeled data, as feature in the NER system. Examples of this approach can be found in the following papers (in addition to the one from @sughodke's comment):
 - [Natural Language Processing (almost) from Scratch](http://www.jmlr.org/papers/volume12/collobert11a/collobert11a.pdf),
 - [Word representations: A simple and general method for semi-supervised learning](https://aclanthology.info/pdf/P/P10/P10-1040.pdf).

This general idea was previously explored with discrete word representation (based on word clustering) instead of word embeddings:
 - [Name Tagging with Word Clusters and Discriminative Training](http://www.aclweb.org/anthology/N04-1043),
 - [Semi-Supervised Learning for Natural Language](https://dspace.mit.edu/bitstream/handle/1721.1/33296/62278990-MIT.pdf).

Best,
Edouard.

**Comment by DavidGOrtega** [comment]
I would recommend this paper also which is the foundation of polyglot ner

https://arxiv.org/pdf/1410.3791.pdf

**Comment by omerarshad** [comment]
any code available for  https://arxiv.org/abs/1709.04820?
