### ISSUE TITLE
N-gram synonym prediction

### ISSUE THREAD

**Issue by AnshulBasia** [facebookresearch/fastText#533]
If I were to get an n-gram synonym to a word, can I do that using fast text? For example, I want to predict "go along" for the word "following".

**Comment by a11apurva** [comment]
I am not very sure, but what I think is that you can use fasttext to generate word-embeddings for your corpus, then you need to need to use/combine some other algorithm.
check out this [paper](https://ufal.mff.cuni.cz/pbml/105/art-leeuwenberg-et-al.pdf) and this [repo](https://github.com/nguyenkh/AntSynDistinction)

**Comment by EdouardGrave** [comment]
Hi @AnshulBasia,

One solution for this problem is to also learn representations for phrases, following the method described in the paper [Distributed Representations of Words and Phrases and their Compositionality](http://papers.nips.cc/paper/5021-distributed-representations-of-words-and-phrases-and-their-compositionality.pdf), by using the word2phrase tool. I would advise to not use subwords in that case, by using the command line option `-maxn 0`.

Best,
Edouard
