### ISSUE TITLE
Does fasttext take care of sentence boundary?

### ISSUE THREAD

**Issue by a11apurva** [facebookresearch/fastText#545]
If I need to train the supervised classifier on a corpus having following kind of content:

```
 __label__A This is sentence 1. This is sentence 2.
 __label__B This is sentence 1. This is sentence 2. . . .This is sentence n.
```

Does the algorithm ignore the periods(full-stops) while moving the context-window over it?
Or does it stops on reaching the period of a sentence and again start from the first word of next sentence?

**Comment by a11apurva** [comment]
I trained and validate my corpus as following :
1. with periods as stated in #333 
2. removing all the periods

Both the method 1 and 2 resulted in approx. same Precision and Recall.

**Comment by matanster** [comment]
I'd be careful drawing much conclusions using the evaluation metrics offered by the fasttext executable, they are extremely crude, at least for multi-label classification. At least try something like AUC or Jaccard accuracy if you really think you can squeeze more.

**Comment by EdouardGrave** [comment]
Hi @a11apurva  and @matanster,

Thank you for raising this issue!

You are correct that fastText does not perform any sentence segmentation. It considers that each line corresponds to one example, whether it contains one or multiple sentences. The reason is that, for some application, one might want to classify longer text than sentences. Moreover, sentence segmentation is language dependent, and we want our classifier to be as much language agnostic as possible.

We thus leave sentence segmentation (if needed) as a preprocessing step that must be performed by the user.

Best,
Edouard.
