### ISSUE TITLE
words starting from capital and small letters in data??

### ISSUE THREAD

**Issue by Sandy4321** [facebookresearch/fastText#576]
this code and data use from 
https://fasttext.cc/docs/en/english-vectors.html
```
import io

def load_vectors(fname):
    fin = io.open(fname, 'r', encoding='utf-8', newline='\n', errors='ignore')
    n, d = map(int, fin.readline().split())
    data = {}
    for line in fin:
        tokens = line.rstrip().split(' ')
        data[tokens[0]] = map(float, tokens[1:])
    return data
fname = 'crawl-300d-2M.vec'
my_data = load_vectors(fname)
```

gives this 
this size of data
len(my_data)
1999995
then
list of keys
z = list(my_data.keys())

gives keys for words starting from capital and small letters
'Nevertheless' in z
True
'nevertheless' in z
True
'trip' in z
True
'Trip' in z
True

so there are not 2 million words but less by 2 times?

**Comment by EdouardGrave** [comment]
Hi @Sandy4321,

We decided to keep the casing when training these models for several reasons. First, for some words, such as `Apple` and `apple`, the capitalized and non-capitalized words are likely referring to different things, and therefore, should have different representations. Second, in some NLP pipelines, the words are not lowercased, and it is therefore important to also have a representation for capitalized words (in order to avoid out-of-vocabulary words).

Best,
Edouard.
