### ISSUE TITLE
.vec and .bin output different word vectors from pretrained Chinese vectors

### ISSUE THREAD

**Issue by martin0258** [facebookresearch/fastText#583]
Things I use:
- Official pretrained Chinese vectors downloaded from [Chinese: bin+text](https://s3-us-west-1.amazonaws.com/fasttext-vectors/wiki.zh.zip)
- fastText built from master branch (25d0bb04bf43d8b674fe9ae5722ef65a0856f5d6)

Results I got:
```
$ grep '^</s>' wiki.zh.vec
</s> 2.6678 5.4073 -0.057711 4.4372 -0.60107 [...]

$ echo "</s>" | ./fasttext print-word-vectors wiki.zh.bin
</s> -0.0027665 0.0026107 -0.0020687 -0.00067994 0.0016234 [...]
```

Can anyone explain why the vectors are different? Not sure whether it's a bug or not. 

 My understanding is fastText returns the mean of n-grams when using `print-word-vectors wiki.zh.bin`, but the only subword of `</s>` is itself (see my python result below), so the outputs from `.vec` and `.bin` should be the same?

```python
>>> from fastText import load_model
>>> model = load_model("wiki.zh.bin")
>>> model.get_subwords("</s>")
(['</s>'], array([0]))
```

**Comment by EdouardGrave** [comment]
Hi @martin0258,

Thank you for reporting this issue!

I believe this problem is due to the fact that we changed how fastText treats the special characters added at the beginning and end of words when computing the subwords (we add `<` and `>` before computing the subwords, see [dictionary.cc#L192](https://github.com/facebookresearch/fastText/blob/master/src/dictionary.cc#L192)). When `minn` is equal to `1`, we decided to exclude these special characters from the list of subwords (see [dictionary.cc#L182](https://github.com/facebookresearch/fastText/blob/master/src/dictionary.cc#L182)). Unfortunately, the Wikipedia models were trained before this change was pushed to the code.

We will update the affected models shortly.

Best,
Edouard.

**Comment by EdouardGrave** [comment]
Hi @martin0258,

We have updated the pre-trained wiki models, so that the word vectors obtained using the binary model correspond to the one in the text file. However, please note that this issue will still concern out-of-vocabulary words! I would strongly suggest to use our newer models, which were trained on common crawl data in addition to Wikipedia. These are available at [word vectors for 157 languages](https://fasttext.cc/docs/en/crawl-vectors.html).

Best,
Edouard.

**Comment by jkleiser** [comment]
Hi @EdouardGrave,

I'm glad the models have been updated. Would it be possible to include some date and/or filesize info on the [download](https://fasttext.cc/docs/en/crawl-vectors.html) page so it will be easier to know if some model has been updated?
