### ISSUE TITLE
Discard word on predict stage?

### ISSUE THREAD

**Issue by rafael-aero** [facebookresearch/fastText#59]
When using the model for predicting a label, the prediction sometimes returns n/a, which I traced back to the dictionary.cc file, method Dictionary::getLine:

`if (type == entry_type::word && !discard(wid, uniform(rng))) {`

that seems to be randomly discarding words from the input line based on a uniform distribution and a probability that comes from the model training.

Is it correct to have this behavior on the predict phase? Although I see the point on having this for the training phase (to avoid overfitting the input data), it seems that this would lead to non-deterministic behavior when using a trained model after.

**Comment by EdouardGrave** [comment]
Words are not discarded in the supervised setting, c.f. the method `Dictionary::discard`:
`if (args.model == model_name::sup) return false;`

The predict function returns `n/a` if the line is empty or if all the words are out-of-vocabulary (either because they do not appear in the training file, or their counts are below the `minCount` threshold).

**Comment by rafael-aero** [comment]
Thanks! I realized now that the other models don't go through the predict method, as they're used only for creating the word vectors... 
Anyway, the problem on my code was due to two instances of the Args class being created in memory, and just one being loaded (of course not the right one) - I thought Args was passed to each other class, but now I see it's being used as a global variable.
