### ISSUE TITLE
FastText for Information Extraction (NER)

### ISSUE THREAD

**Issue by jfatine** [facebookresearch/fastText#592]
I'm trying to train FastText for performing Information Extraction (Named Entity Recognition) on a corpus where the positive examples (speakers) are not organized one per line, like in the paragrapgh below.
Can FastText be trained on this kind of input? 
Goal: I want that it predicts labels for a paragraph containing no labels.

"The Student Alumni Relations Council (SARC) invites you to a Career Talk featuring __label__speaker Andrew Gault HS'80 HNZ'94 and three university speakers, __label__speaker Mary Francis McLaughlin (volunteer and community service opportunities), __label__speaker Jessie Ramey (research opportunities) and __label__speaker Judi Mancuso (part-time work-study summer and internship opportunities) on Tuesday January 31 at 7:00 P M in the Carnegie Conference Room 1st Floor Warner Hall."

**Comment by loretoparisi** [comment]
@jfatine this is pretty interesting, but I'm not sure how your dataset is organized actually.

**Comment by jfatine** [comment]
The dataset contains 2 text corpus, one for training and the other for testing. Each corpus contains a set of paragraphs like the one above.

**Comment by ericxsun** [comment]
Wow, that's pretty interesting. Any progress have been made?

**Comment by EdouardGrave** [comment]
Hi @jfatine,

One potential solution for this problem is to use a [conditional random fields](https://en.wikipedia.org/wiki/Conditional_random_field) (CRF), and use the pre-trained fastText word vectors as features. Unfortunately, fastText does not contain a CRF implementation for the moment, and you will need to rely on a third party tool for this matter.

Best,
Edouard.
