### ISSUE TITLE
Question: How to analyze sentence similarity under fastText?

### ISSUE THREAD

**Issue by leonardgithub** [facebookresearch/fastText#64]
I have a requirement on hand, e.g. user input some text (Chinese) inside the input box of the app, and we need to redirect user to other pages according to user's semantic meaning. 
So, can fastText do some helps on this? 
Thanks!

**Comment by amirothman** [comment]
You can analyze the sentence similarity by averaging the value of the word vectors and find the nearest neighbour according to a similarity measure (e.g. cosine distance). You might want to benchmark with simpler models like tf-idf, bag-of-words, etc.

**Comment by piotr-bojanowski** [comment]
Hi,

As this is not an issue per-se, I would recommend posting this kind of questions on the FB fasttext users group [](https://www.facebook.com/groups/1174547215919768/). 
Please note that since commit d652288bad3d5e30a350c67599df4c92dc471960, there is an option for printing vectors for a paragraph after supervised training. 

Hope this helps!

**Comment by leonardgithub** [comment]
@amirothman  @piotr-bojanowski  Thank you very much. By the way, @piotr-bojanowski,  Is it possible to commit a question issue on this github?
