### ISSUE TITLE
Some code in computeSubwords method,What is the purpose of this code?

### ISSUE THREAD

**Issue by quantumcs** [facebookresearch/fastText#646]
Hi.
`c
 if ((word[i] & 0xC0) == 0x80) continue;
`
in computeSubwords .
What is the purpose of this code ? skip over sth? Thanks for your answer.

**Comment by loretoparisi** [comment]
In my understanding this is a Unicode check of `word[i]` through the bit mask `0xC0` that is ` 11 00 00 00` against '0x80` that is `10 00 00 00`.

So the AND `word[i] & 0xC0` gets the top two bits, and compare to `0x80` to check f the top two bits of the value are not equal to `10`. This because in `UTF-8`, all bytes that begin with the bits 10 are the bytes of a multi-byte sequence (like a double-byte sequence).

See [here](https://stackoverflow.com/a/3911566/758836) for more details, and [Joel Spolsky about Unicode](https://www.joelonsoftware.com/2003/10/08/the-absolute-minimum-every-software-developer-absolutely-positively-must-know-about-unicode-and-character-sets-no-excuses/)

**Comment by quantumcs** [comment]
Thank you for your answer.
So then, that means this code will skip over the byte that can not be a single word.
but If the sentence is encoded in other ways, not UTF-8, is it possible?will there be any problems at this time?
thinks.

**Comment by quantumcs** [comment]
Thank you for your answer.
So then, that means this code will skip over the byte that can not be a single word.
but If the sentence is encoded in other ways, not UTF-8, is it possible?will there be any problems at this time?
Thanks.
