### ISSUE TITLE
How can I get the  probabilities of the prediction in text classify in python?

### ISSUE THREAD

**Issue by DachuanZhao** [facebookresearch/fastText#748]
[https://github.com/facebookresearch/fastText/blob/master/python/doc/examples/train_supervised.py](https://github.com/facebookresearch/fastText/blob/master/python/doc/examples/train_supervised.py)
In this example,I notice that I can use `model.predict ` get the predict label.
But how can I get the probability?
`results = model.predict("a sentence")`
I think results[1][0] is not the probability because it is sometimes more than 1

**Comment by Celebio** [comment]
Hi @DachuanZhao ,
`results[1][0]` should give you the probability (given there is at least one prediction). Can you provide the model that gives you a probability > 1 ?

Regards,
Onur

**Comment by DachuanZhao** [comment]
Hi @Celebio ,
I have invited you to the repository for debug
https://github.com/DachuanZhao/fastTextProbility/invitations

**Comment by Celebio** [comment]
Hi @DachuanZhao ,
This is a floating point precision issue due to composing log and exp functions.
Consider the following code : 
```
#include <iostream>
#include <cmath>

float std_log(float x) {
  return std::log(x + 1e-5);
}

int main(int argc, char *argv[]){
    float f = 1.0;
    std::cout << f << std::endl;
    std::cout << std_log(f) << std::endl;
    std::cout << std::exp(std_log(f)) << std::endl;
}
```
you will get
```
1
9.99995e-06
1.00001
```
This is the same happening here, except you also get some small errors when the value is converted to python in pybind.

As a workaround, I suggest to modify [this line](https://github.com/facebookresearch/fastText/blob/master/src/loss.cc#L27) to `return std::log(x + 1e-10);`

Thank you for raising the question. Hopefully it helps.

Best regards,
Onur
