### ISSUE TITLE
MemoryError: bad allocation

### ISSUE THREAD

**Issue by Jefffish09** [facebookresearch/fastText#782]
When I train supervised text classifiers, it shows "MemoryError: bad allocation"
![image](https://user-images.githubusercontent.com/44800122/55927341-47e2f380-5c47-11e9-83d7-343124294877.png)

The size of train-data.txt is 7.38GB, my PC's total RAM is 8GB, but the available RAM is less than 3GB. My system is Windows 7 x64.

Here is my arguments:
![image](https://user-images.githubusercontent.com/44800122/55927464-bf188780-5c47-11e9-8f89-443c175f2f39.png)

Is there any solution for this error?

**Comment by EdouardGrave** [comment]
Hi @Jefffish09,

This is indeed probably because your system does not have enough memory. Please note that fastText never loads the full dataset in memory, so here, the problem is probably due to the size of the model. You can try reducing it by changing the `minCount` parameter (which will discard more words, but lead to a smaller vocabulary and thus model), the `dim` parameter (which will reduce the dimension of the model and hence the size), or the `bucket` parameter (which will reduce the number of buckets in which the ngram features are hashed ; the default is 2M, you can try 500k for example).

I hope this help fixing the issue.

Best,
Edouard
