### ISSUE TITLE
How to use fasttext vectors in a tensorflow embedding layer?

### ISSUE THREAD

**Issue by datistiquo** [facebookresearch/fastText#812]
Hey,

I just struggle to find out how can I use Fasttext wordvectors for OOV word (in general) in a keras/tensorflow embedding layer. There is nothing out there. Maybe someone has thought of that too and has some hints for me?

The way via word embedding look up works via indices like
`tf.nn.embedding_lookup(word_embeddings, x)`

And you could have an index for one OOV. But how can I assign a specific vector (from a different and custom source like fasttext) at runtime?

I am not so experienced with the inner working of tensorflow embedding_lookup.

Up to know I handle OOV words by splitting the OOV in known subwords! So I make more words out of a OOV.

**Comment by Celebio** [comment]
Hi @datistiquo ,
I believe this is not related to fasttext, but to tensorflow.

Regarding fasttext, in order to get the wordvectors for OOV, it is the same as OOV : you just call `get_word_vector` from python or, `print-word-vectors` from the command line.
 
I will close this issue. If you have any question related to fasttext, feel free to re-open it.
Best regards,
Onur
