### ISSUE TITLE
Segmentation fault when importing both fastText and pytorch

### ISSUE THREAD

**Issue by travel-go** [facebookresearch/fastText#828]
hello:
pytorch and fastText cannot import together.

**Comment by Celebio** [comment]
Hi @travel-go ,
The issue seems very similar to https://github.com/facebookresearch/fastText/issues/701. Could you try to install fasttext from [pypi](https://pypi.org/project/fasttext/) and import `fasttext` (note lower `t`) ? Please note this is just to check if it fixes your issue : the version on pypi is obsolete and will be updated soon, so do not rely on it for your code.

Best regards,
Onur

**Comment by travel-go** [comment]
Hi：
Thank you for your reply. I will try it.
Best regards， 
travel-go

**Comment by Celebio** [comment]
Hi @travel-go ,
Did you manage to make it work?

Onur

**Comment by DaPenggg** [comment]
@Celebio have you solved the issue?
