### ISSUE TITLE
PicklingError: Could not serialize object: TypeError: can't pickle fasttext_pybind.fasttext objects

### ISSUE THREAD

**Issue by bellaDS** [facebookresearch/fastText#849]
I built a fasttext classification model in order to do sentiment analysis for facebook comments,  (using pyspark 2.4.1 on windows), when i use the prediction model function to predict the class of a sentence , the result is a tuple with the form below:

[('__label__positif', '__label__négatif', '__label__neutre', 0.8947999477386475, 0.08174632489681244, 0.023483742028474808)]

but when i tried to apply it to the column "text" i did this : 

from pyspark.sql.types import *
from pyspark.sql.functions import udf, col
import fasttext
schema = StructType([
    StructField("pos", StringType(), False),
    StructField("neg", StringType(), False),
    StructField("ntr", StringType(), False),
    StructField("pr_pos", DoubleType(), False),
    StructField("pr_neg", DoubleType(), False),
    StructField("pr_ntr", DoubleType(), False)
])

udf_label = udf(lambda words : predictClass(words), schema) 
df = df.withColumn("classe", udf_label(col('text')))

df.select('classe').show()

and i get this errror : PicklingError: Could not serialize object: TypeError: can't pickle fasttext_pybind.fasttext objects

can someone help me please !!!

**Comment by Celebio** [comment]
Hi @bellaDS ,
As [Maksym](@MKisilyov) mentionned [here](https://www.facebook.com/groups/1174547215919768/?comment_id=2913166652057807&comment_tracking=%7B%22tn%22%3A%22R%22%7D&post_id=2913128998728239), this is because the object you try to serialize contains native code so it is not possible. You can use `save_model` to save it on the disk and retrieve it later.

I am closing this issue, feel free to re-open it if you have further questions.

Best regards,
Onur

**Comment by bellaDS** [comment]
Thank you for your answer and that's what I've done , in fact I came across the same answer from  Maksym and it works for me !

**Comment by Celebio** [comment]
Glad to hear that! Feel free to ask any question related to fastText here or in the facebook group.

Onur

**Comment by sandychales** [comment]
Hi @Celebio 
If I want to use GridSearch in sklearn, the best way for me is to package fasttext model by inheritting 'BaseEstimator' class.  (The code is showed  below)

`from sklearn.model_selection import cross_validate, cross_val_score
from sklearn.base import BaseEstimator
from sklearn.metrics import accuracy_score
import fasttext

class FasttextSupervisedEstimator(BaseEstimator):

    def __init__(self, model_dir=None, input=None, lr=0.1, dim=100, ws=5, epoch=5,minCount=1,
                minCountLabel=1, minn=0, maxn=0, neg=5, wordNgrams=1,
                loss='softmax',bucket=2000000, lrUpdateRate=100, t=0.0001,
                verbose=2, pretrainedVectors=''):

        self.input = input
        self.lr=lr
        self.dim=dim
        self.ws=ws
        self.epoch=epoch
        self.minCount=minCount
        self.minCountLabel=minCountLabel
        self.minn=minn
        self.maxn=maxn
        self.neg=neg
        self.wordNgrams=wordNgrams
        self.loss=loss
        self.bucket=bucket
        self.lrUpdateRate=lrUpdateRate
        self.t=t
        self.verbose=verbose
        self.pretrainedVectors=pretrainedVectors
        
        if os.path.exists(model_dir):
            self.ft_clf = fasttext.load_model(model_dir)
        else:
            self.ft_clf = None
        
    def fit(self, features, labels): 
        file = self.input
        store_ft_file(file, features, labels)
        self.ft_clf = fasttext.train_supervised(
        input=self.input,
        lr=self.lr,
        dim=self.dim,
        ws=self.ws,
        epoch=self.epoch,
        minCount=self.minCount,
        minCountLabel=self.minCountLabel,
        minn=self.minn,
        maxn=self.maxn,
        neg=self.neg,
        wordNgrams=self.wordNgrams,
        loss=self.loss,
        bucket=self.bucket,
        lrUpdateRate=self.lrUpdateRate,
        t=self.t,
        verbose=self.verbose,
        pretrainedVectors=self.pretrainedVectors
                                       )
        return self
    
    def score(self, features, labels):
        pred_topK_labels, pred_topK_proba = self.ft_clf.predict(features)
        pred_labels = np.squeeze(np.array(pred_topK_labels)) 
        
        score = accuracy_score(labels, pred_labels)
        return score
        
    def predict(self, features):
        predicts = self.ft_clf.predict(features)
        return predicts`

But when I want to simply save this estimator, I have to save fasttext model individually instead of using joblib, or it will raise an error.  
If there is a more elegant  way to solve this? 
Thanks a lot

**Comment by hafiz031** [comment]
I am facing the error. But the context is different: [ERROR:root:can't pickle fasttext_pybind.fasttext objects](https://stackoverflow.com/q/69430747/6907424)
