### ISSUE TITLE
Migration Website to Docusaurus 2 Alpha

### ISSUE THREAD

**Issue by aswathkk** [facebookresearch/fastText#928]
Hi there! The Docusaurus team is currently developing Docusaurus 2 and are almost done with an MVP that doesn't include translations and versioning features, which means there's feature parity with your website's current usage of Docusaurus.

Docusaurus 2 brings about many improvements:

- Client-side rendering with prerendering (site renders without JavaScript!)
- More flexible appearance - Customizable layouts, CSS modules, etc
- Embeddable interactive React components within markdown via MDX

I will be your POC in helping you throughout the migration process. Let me know what you think!

cc @yangshun @endiliey

**Comment by yangshun** [comment]
Sorry @lzhuor has expressed interest in migrating this website first since he followed the instructions by commenting on https://github.com/facebook/docusaurus/issues/1834. You should comment on the issue to let us know about this.

Anyway you have the Redux Starter Kit to migrate and that will keep you busy for a while.

**Comment by aswathkk** [comment]
@yangshun It's alright!
I will work on Redux Starter Kit docs.
