### ISSUE TITLE
Some test data are classified as 'n/a'

### ISSUE THREAD

**Issue by plagad** [facebookresearch/fastText#97]
I use fasttext to classify text into two class. Some data are classified as 'n/a'.
- What's 'n/a' means.
- How to avoid 'n/a' result.

**Comment by Doubledongli** [comment]
Who knows the format of input file?

**Comment by plagad** [comment]
Both train and test input files are UTF-8

**Comment by Doubledongli** [comment]
Hi,Can you give me a origin input fille? I want to make a test,3Q.

**Comment by plagad** [comment]
@Doubledongli I can give you a sample of input files. The original train input file have ~2,000 data.
You can download the sample of input files [here](https://drive.google.com/drive/folders/0B0bwUtcjVTEqRTdCZjdzcDZKajA?usp=sharing).

**Comment by Doubledongli** [comment]
Can you send this to my E-mail? I can not open the link,
Double_dongli@foxmail.com

**Comment by plagad** [comment]
@Doubledongli I sent that email to you. Thank you for your time.

**Comment by Doubledongli** [comment]
Thanks so much

**Comment by peijj0924** [comment]
I got this problem too. Do you know the answer? Please tell me, thank you!

**Comment by j-min** [comment]
Got same problem

**Comment by EdouardGrave** [comment]
Hi all,

At prediction time, fastText ignores empty lines and outputs `n/a` for such lines. A line is considered as empty either because it does not contain any words, or because all the words are out-of-vocabulary (i.e. words that were not in the training set or seen less than `–minCount`).

A potential solution not to have empty lines is to add a "dummy" word to all lines, such as `</s>`.  This can easily be done with the awk command line tool:
```
awk '{print $0" </s>"}' train.txt
awk '{print $0" </s>"}' test.txt
```

We will change this behavior in the future.

**Comment by jowagner** [comment]
If you make this change, please add an option to not add the extra token. It can be nice to know when the classifier does not have sufficient information to make a prediction. Do I assume correctly that the dummy word will push the model towards predicting the majority class? Could this potentially change predictions for lines that contain in-vocabulary words (other than the dummy word) where there is a close tie between classes?
